apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-filter-frontend
  namespace: phone-filter
  labels:
    app: phone-filter-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: phone-filter-frontend
  template:
    metadata:
      labels:
        app: phone-filter-frontend
    spec:
      containers:
      - name: frontend
        image: unibna/phone-filter-frontend:2.0.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 150m
            memory: 225Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
      restartPolicy: Always
