apiVersion: v1
kind: Service
metadata:
  name: phone-filter-frontend-svc-nodeport
  namespace: phone-filter
spec:
  type: NodePort
  selector:
    app: phone-filter-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30380
